MORTGAGE_DATA = {
    "properties": [
        {
            "id": "PROP-001",
            "address": "123 Oak Street, Springfield, IL 62701",
            "owner": "Sarah Johnson",
            "loan_amount": 285000,
            "current_balance": 241500,
            "monthly_payment": 1842.50,
            "interest_rate": 4.25,
            "loan_type": "30-year fixed",
            "origination_date": "2019-03-15",
            "status": "current",
            "payments_behind": 0,
        },
        {
            "id": "PROP-002",
            "address": "456 Maple Ave, Springfield, IL 62702",
            "owner": "Michael Chen",
            "loan_amount": 320000,
            "current_balance": 298700,
            "monthly_payment": 2150.00,
            "interest_rate": 5.75,
            "loan_type": "30-year fixed",
            "origination_date": "2022-08-01",
            "status": "delinquent",
            "payments_behind": 3,
        },
        {
            "id": "PROP-003",
            "address": "789 Elm Drive, Springfield, IL 62703",
            "owner": "Maria Rodriguez",
            "loan_amount": 195000,
            "current_balance": 167200,
            "monthly_payment": 1285.00,
            "interest_rate": 3.875,
            "loan_type": "30-year fixed",
            "origination_date": "2020-11-20",
            "status": "in_foreclosure",
            "payments_behind": 6,
        },
        {
            "id": "PROP-004",
            "address": "321 Pine Road, Springfield, IL 62704",
            "owner": "James Wilson",
            "loan_amount": 415000,
            "current_balance": 389000,
            "monthly_payment": 2780.00,
            "interest_rate": 6.125,
            "loan_type": "30-year fixed",
            "origination_date": "2023-01-10",
            "status": "delinquent",
            "payments_behind": 2,
        },
        {
            "id": "PROP-005",
            "address": "555 Cedar Lane, Springfield, IL 62705",
            "owner": "Angela Thompson",
            "loan_amount": 178000,
            "current_balance": 112400,
            "monthly_payment": 1125.00,
            "interest_rate": 3.50,
            "loan_type": "15-year fixed",
            "origination_date": "2017-06-01",
            "status": "current",
            "payments_behind": 0,
        },
    ],
    "foreclosure_resources": [
        {
            "name": "HUD Housing Counseling",
            "url": "https://www.hud.gov/counseling",
            "phone": "1-800-569-4287",
            "description": "Free or low-cost housing counseling services approved by HUD.",
        },
        {
            "name": "Making Home Affordable",
            "url": "https://www.makinghomeaffordable.gov",
            "phone": "1-888-995-4673",
            "description": "Government program to help homeowners avoid foreclosure.",
        },
        {
            "name": "Legal Aid Society",
            "url": "https://www.legalaid.org",
            "phone": "1-800-532-1275",
            "description": "Free legal assistance for homeowners facing foreclosure.",
        },
    ],
    "loss_mitigation_options": [
        "Loan Modification",
        "Forbearance Agreement",
        "Repayment Plan",
        "Short Sale",
        "Deed in Lieu of Foreclosure",
        "Partial Claim",
    ],
}
